apiVersion: batch/v1
kind: CronJob
metadata:
  name: reddit-bot
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reddit-bot
              image: dima032398485/reddit_bot:latest
              imagePullPolicy: Always